### ISSUE TITLE
No 32-bit pre-compiled binary package.

### ISSUE THREAD

**Issue by SamAlex90** [jaburns/NintendoSpy#22]
Gives this error in Windows 7 Ulitmate x86:

"The version of this file is not compatible with the version of windows you're running. Check your computers system information to see weather you need an x86 (32bit) or x64 (64bit) version of the program, and then contact the software publisher"

**Comment by jaburns** [comment]
You should be able to compile it for 32-bit Windows, I don't think there's anything specifically x64 dependent.

**Comment by maueroats** [comment]
This issue should go in some kind of FAQ. You could request somebody make a 32-bit build, but at least say something like "executable requires 64 bit windows" on the main download page.

**Comment by jaburns** [comment]
You're right I'll make the change to the download page.  The solution might also need some tweaking to point to the right SlimDX DLL for x86 builds as well.

**Comment by abductedPlatypus** [comment]
I setup the project to select the right SlimDX binary at build time, so building these will be rather easy.
