### ISSUE TITLE
USB controllers

### ISSUE THREAD

**Issue by killinninja49** [jaburns/NintendoSpy#28]
So I have been having a problem with NintendoSpy recently I have just recently encountered this problem and don't know how to resolve it, I've looked through all the xml files and haven't seen any problems. I am currently using a PS4 controller, It identifies well on joy.cpl but  Any help is appreciated, Thanks.

**Comment by abductedPlatypus** [comment]
Could you describe the problem you encounter? 

Given the age of this post, and the lack of a clear description I suggest to close this issue, unless replied to within a week.

**Comment by jaburns** [comment]
Agreed. @killinninja49 we'll need a more thorough description of the issue to be able to do anything about it, otherwise the issue will be closed.

**Comment by killinninja49** [comment]
@Jaburns I resolved this problem a few months ago, it was just a problem with my PC having 4 of the same drivers installed and that interfering with the Controller
