### ISSUE TITLE
Need to be able to select between multiple gamepad / xinput sources.

### ISSUE THREAD

**Issue by jaburns** [jaburns/NintendoSpy#4]
If the player has more than one gamepad plugged in, we shouldn't just pick the first one.

**Comment by katafii678** [comment]
hi, so i connected my Retrolink nintendo64 usb controller (with no adapter) on my computer and ALL the inputs are wrong except the anolog stick. please help :)

**Comment by jaburns** [comment]
What input source did you select? Generic gamepad? If so, then you have to configure the skin to use the proper buttons.

**Comment by abductedPlatypus** [comment]
I implemented this, expect it tomorrow on my branch and as pull request.
