### ISSUE TITLE
Classic Controller Support?

### ISSUE THREAD

**Issue by DarkXoa** [jaburns/NintendoSpy#41]
Will your arduino build work for intercepting inputs from a Wii Classic(Pro), NES Classic, or SNES Classic controller?

If not, would you be willing to add this functionality? I would gladly donate to help support this development.

Edit: I'm personally most interested in the Wii Classic Pro controller, for the record

**Comment by jaburns** [comment]
The NintendoSpy as-is would not work with those controllers. I haven't spent a lot of time investigating how information is sent from nunchuck-like controller extensions to the WiiMote, but it looks like the data is encrypted. Unfortunately though, I personally don't have the time or intention to build support for Wii controllers myself, sorry.

**Comment by jaburns** [comment]
@DarkXoa Looks like @Zas32x added support for Classic Controller in PR #45 which is now merged.

**Comment by Zas32x** [comment]
https://www.youtube.com/watch?v=nkNZ5fO07JE

**Comment by DarkXoa** [comment]
Can't figure out how to use this. I'm guessing I have to wait for a new release?
