### ISSUE TITLE
v1.10.1 input delay

### ISSUE THREAD

**Issue by niss3** [jaburns/NintendoSpy#48]
Hey!

I made a Nintendospy recently. I didn't use the original arduino uno but a third party version. Do you think that might be the cause of "input delay"? Or is there any option in v1.10.1 that can add or remove input delay?

Thank you for answering!

**Comment by niss3** [comment]
Update: The original Arduino Uno didn't solve the problem. And the input delay appears to be 250ms.

**Comment by jaburns** [comment]
Some amount of input delay is inevitable given all of the steps between reading the controller and rendering it on the PC, compared to the direct input to the console. If you want them to sync up on stream you'll have to add a small delay to the video feed. There's also an existing issue for tracking a feature that adds delay to the controller renderer, so I'm closing this issue.

https://github.com/jaburns/NintendoSpy/issues/36
