### ISSUE TITLE
Shadow presses and flickering?

### ISSUE THREAD

**Issue by melink14** [jaburns/NintendoSpy#49]
I just wired up my super Nintendo controller and it works quite well.

I noticed two problems:

Some buttons when pressed cause other buttons to flicker.
Those other buttons also flicker when they're held down themselves.

D-pad: works normal
L/R: flicker
Select: works fine causes L to flicker
Start: works fine causes R to flicker
Y/B: cause X/A to flicker respectively
X/A flicker when held down.

This seems pretty consistent so I wonder if it means I wired something wrong or if there's something else I should debug.

Thanks!

**Comment by melink14** [comment]
I saw some other issues mentioned flickering options but I can't seem to find them to change.

Mostly I'm trying to figure out if it could be caused by a bad job wiring or if there's something else I should check offhand.

**Comment by jaburns** [comment]
The NES/SNES implementation is a lot more straightforward software-wise than the N64/GCN one, so I'd expect if you're seeing flickering it's either an issue with your controller itself, or the custom wiring. The anti-flickering stuff people are usually talking about in regards to NintendoSpy is for N64/GCN where it's harder to get a good read off the line from an Arduino.
