### ISSUE TITLE
Support for Pro Micro

### ISSUE THREAD

**Issue by texztech** [jaburns/NintendoSpy#56]
Hello I know that this project works on the arduino Uno. My problem is I wanted to miniaturize the adapter so it would just plug inline with the controller. I have the Pro Micro from https://www.amazon.ca/XCSOURCE-ATMEGA32U4-Arduino-Leonardo-TE463/dp/B01F78T2FS

thank you for your time.

**Comment by PedrOwl** [comment]
If you really want to miniaturize without any type of problem, the arduino nano is good, but i don't know about what you linked.

I use it and it's enough. you don't have to change the code to make it works with a nano.

https://store.arduino.cc/arduino-nano

**Comment by texztech** [comment]
That seems to work thank you.
