### ISSUE TITLE
Where is the .exe file?

### ISSUE THREAD

**Issue by TheGameBoyBoy** [jaburns/NintendoSpy#57]
I'm new, and in your read me, it says to open the .exe file, but there isn't one. Can anybody help me?
![screenshot_25](https://user-images.githubusercontent.com/48041053/53464303-58306d80-3a0f-11e9-90e5-ae8d703f84ee.png)

**Comment by melink14** [comment]
It looks like you downloaded the source code. https://github.com/jaburns/NintendoSpy/releases/tag/v1.10.1

The first link on that page should have the exe
