### ISSUE TITLE
Question about Keybinding

### ISSUE THREAD

**Issue by wellzish** [jaburns/NintendoSpy#79]
Working off of the example i have set a combination of controller inputs to output "CAPLOCK" as a hotkey output. However this is not being triggered. All inputs work as intended on display. Also should i adjust the Keybinding XML in the root of the folder or generate a separate keybindings xml in the specific skin folder. Thank You for your time

**Comment by jaburns** [comment]
CAPLOCK or CAPSLOCK with an S. Should be the latter
