### ISSUE TITLE
Support for USB Pro Controller?

### ISSUE THREAD

**Issue by royaltongue** [jaburns/NintendoSpy#82]
I have a USB Pro Controller for the Nintendo Switch that I'd like to use NintendoSpy with. It seems like it would be similar, but USB uses Data+ and Data-, so the existing guide/code wouldn't support it.

Would it be possible to add support for this?

**Comment by jaburns** [comment]
Unfortunately the USB signal would probably be too complex/fast to parse with an Arduino hack like this. If you can think of a way to do it PRs are welcome, but I'm not actively developing this project currently.
