### ISSUE TITLE
SNES Controller Input does not work.

### ISSUE THREAD

**Issue by LennnaLee** [jaburns/NintendoSpy#84]
I followed the build instructions and managed to get my extension cable to splice into 5 signals. I plan to power the controller with the Arduino's 5v and Ground as I need the input display without the console. Theoretically, it should work, but it doesn't seem to. Please assist and all help is welcome. Find attached a picture of my setup.

https://imgur.com/gallery/ZGqi8u5

**Comment by jaburns** [comment]
Where is the part that plugs into the SNES? The inputs that go to the Arduino are meant to also still go to the SNES, like the Arduino wires tap the signals in the controller wire, they don't replace them.
