### ISSUE TITLE
Analogue Stick Range Uneven

### ISSUE THREAD

**Issue by VeritasDev** [jaburns/NintendoSpy#85]
It appears as though the x and y range for the analogue stick values are not equally applied in the positive and negative direction.

<img width="1291" alt="Screenshot 2021-04-20 113912" src="https://user-images.githubusercontent.com/51370386/115425105-4f8de900-a1cd-11eb-9237-2612b0dd7352.png">
<img width="1290" alt="Screenshot 2021-04-20 114107" src="https://user-images.githubusercontent.com/51370386/115425120-54eb3380-a1cd-11eb-8f34-fe7f3207892a.png">
<img width="1291" alt="Screenshot 2021-04-20 113840" src="https://user-images.githubusercontent.com/51370386/115425122-5583ca00-a1cd-11eb-8889-87a942984e48.png">
<img width="1289" alt="Screenshot 2021-04-20 113906" src="https://user-images.githubusercontent.com/51370386/115425123-5583ca00-a1cd-11eb-9e36-2ddd09f64fd1.png">
<img width="1290" alt="Screenshot 2021-04-20 113909" src="https://user-images.githubusercontent.com/51370386/115425124-5583ca00-a1cd-11eb-998a-2449219b8197.png">

**Comment by VeritasDev** [comment]
Doing some more testing with a debug image:

<img width="636" alt="Screenshot 2021-04-20 115709" src="https://user-images.githubusercontent.com/51370386/115427635-a399cd00-a1cf-11eb-8b63-fcf1c4a3cf2f.png">
<img width="634" alt="Screenshot 2021-04-20 115703" src="https://user-images.githubusercontent.com/51370386/115427642-a4cafa00-a1cf-11eb-8d58-7a3ce8bd724f.png">
<img width="633" alt="Screenshot 2021-04-20 115707" src="https://user-images.githubusercontent.com/51370386/115427643-a5639080-a1cf-11eb-88ef-3a3c120d350c.png">

Config:

```
<?xml version="1.0" encoding="UTF-8"?>
<skin name="debug" author="Veritas" type="n64">
    <background name="Default" image="bg.png" />
    <stick image="stick.png" xname="stick_x" yname="stick_y" x="26" y="26" xrange="25" yrange="25" />
</skin>

```

**Comment by VeritasDev** [comment]
Using photoshop to actually look at the resulting range of the stick image, here's the estimated actual resulting x position:

[center] 26
[full left] 10 (-16)
[full right] 47 (+21)

Assuming the range is the ENTIRE min-max range for each dimension, I'd expect the result to be something like:

[center] 26
[full left] 13.5 (-12.5)
[full right] 38.5 (+12.5)

![Untitled-1](https://user-images.githubusercontent.com/51370386/115429247-3c7d1800-a1d1-11eb-872a-f8928753a352.png)


Assuming its the one-way range, I'd expect:

[center] 26
[full left] 1 (-25)
[full right] 51 (+25)

![Untitled-2](https://user-images.githubusercontent.com/51370386/115429265-40109f00-a1d1-11eb-8b7e-c1b27c685589.png)

**Comment by VeritasDev** [comment]
Interestingly enough I tried this with another controller and it appears to be behaving as expected... That of course means either my controller is sending invalid stick values OR values that the code doesn't expect/adjust for?

**Comment by jaburns** [comment]
Yeah I think it's probably the stick not maxing out in the one direction for that one controller, since the code that displays the position is relatively simple. It would be nice to have a way to compensate for that in the setup XML though, like splitting the range between negative and positive values. I'll close this and reference it from a feature ticket for that.
