### ISSUE TITLE
Requesting Fix for SNES 2 Gamecube Adapters on NintendoSpy SNES

### ISSUE THREAD

**Issue by Nippo4512** [jaburns/NintendoSpy#86]
Not so much a request, rather at least a way to inform me on how to actually change these values. 

I have bought myself a SNES to Gamecube Adapter, and I currently have an SNES input display. I chained them up so it goes from Gamecube -> SNES to Gamecube -> SNES Input Display -> PC. The inputs show on my PC and work fine except for the fact that all inputs are offset by one when referring to the order they appear in the NintendoSpy source code. 

So, in the source code they are shown in this order:
"b", "y", "select", "start", "up", "down", "left", "right", "a", "x", "l", "r", null, null, null, null

However, the adapter offsets these inputs and omits the "b", which has it read like this instead:
"y", "select", "start", "up", "down", "left", "right", "a", "x", "l", "r", null, null, null, null

What this does is have the controller show the B button when actually pressing Y, the Y button when actually pressing Select, etc. 

How would I alter the button configuration so that way the list is shown like this:  null, "b", "y", "select", "start", "up", "down", "left", "right", "a", "x", "l", "r", null, null, null

I have already attempted to do this in SuperNESandNES.cs and played around with some other things to no avail, so I figured it wouldn't hurt to ask here. I don't want to end up buying a specific Gamecube adapter when this one seems to work fine besides this one error. 

Thanks for any help.

**Comment by jaburns** [comment]
Unfortunately I don't know off the top of my head what could be the problem, and I'm not actively working on this project myself. I'll leave the ticket open though in case someone else sees it and can provide some insight.

**Comment by Nippo4512** [comment]
I have actually found a fix a while ago with my specific SNES to GC adapter and my input display. I had to change some things in the Arduino in order for it to fix itself. I'm not sure if I can send files through this directly but if anyone stumbles across this and needs I'm in the input display discord.
