### ISSUE TITLE
Creating a skin

### ISSUE THREAD

**Issue by lexusjude** [jaburns/NintendoSpy#91]
I'm trying to create skins for my controller, but the only problem I've had so far is finding the x and y value to place the buttons & joystick, it's just become a trial and error. Is there a way to get the x and y value placements without having constantly retype it in?

**Comment by jaburns** [comment]
There's no specific tool unfortunately. The way I did it with the built-in skins is use a paint program to find the coordinates, like by hovering the selection tool and reading out the pixel coordinates from where it shows them for the cursor.
